check_database:
  path: /healthcheck/checks/database
  controller: Onisep\IbexaHealthCheckBundle\Controller\DatabaseController::check

check_solr:
  path: /healthcheck/checks/solr
  controller: Onisep\IbexaHealthCheckBundle\Controller\SolrController::check

check_redis:
  path: /healthcheck/checks/redis
  controller: Onisep\IbexaHealthCheckBundle\Controller\RedisController::check

check_index:
  path: /healthcheck/checks
  controller: Onisep\IbexaHealthCheckBundle\Controller\IndexController::check

