services:
  _defaults:
    public: true
    autowire: true
    autoconfigure: true

  Onisep\IbexaHealthCheckBundle\Controller\:
    resource: '../../Controller/*Controller.php'
    tags: ['controller.service_arguments']

  Onisep\IbexaHealthCheckBundle\Check\:
    resource: '../../Check/*Check.php'
